[tool.pyright]
include = ["src"]
exclude = ["**/__pycache__"]
ignore = []
strict = ["src/**.py"]
defineConstant = { DEBUG = true }
stubPath = "src/stubs"

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.11"
pythonPlatform = "Linux"

executionEnvironments = [{ root = "src" }]
